
spring:
  redis: # redis
    host: localhost
    port: 6379
    lettuce:
      pool:
        maxIdle: 5
        maxActive: 20
        maxWait: 10
    timeout: 2000
#logging:
# level:
#  org.hibernate.type.descriptor.sql.BasicBinder: trace